name: Java CI/CD Pipeline

on:
  push:
    branches: [ "master" ]   # change to "master" if your repo uses it

jobs:
  build:
    runs-on: windows-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Verify Java & Maven
        run: |
          java -version
          mvn -version

      - name: Build using Maven
        run: mvn clean install
        working-directory: demo
